apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: cfsrw02l8-nodejs 
  janus-idp.io/tekton: cfsrw02l8-nodejs
  backstage.io/kubernetes-id: cfsrw02l8-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cfsrw02l8-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml